#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.3.0f5_44796c9d3c2c"
#define UNITY_VERSION_FULL_NICE "2019.3.0f5 (44796c9d3c2c)"
#define UNITY_VERSION_BLD 4487532
#define UNITY_VERSION_DATE 1578491132
#define UNITY_VERSION_WIN "2019.3.0.4487532"
#define UNITY_VERSION_BRANCH "2019.3/staging"
